"""add owner_id to taskdb

Revision ID: 14549e1a35ff
Revises: 
Create Date: 2026-06-16 09:54:03.524384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14549e1a35ff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taskdb', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'taskdb', 'userdb', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'taskdb', type_='foreignkey')
    op.drop_column('taskdb', 'owner_id')
    # ### end Alembic commands ###
