"""initial schema

Revision ID: fa753f0f08b5
Revises: 
Create Date: 2026-06-20 09:06:05.439860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'fa753f0f08b5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taskdb', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.add_column('taskdb', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'taskdb', 'userdb', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'taskdb', type_='foreignkey')
    op.drop_column('taskdb', 'category')
    op.drop_column('taskdb', 'owner_id')
    # ### end Alembic commands ###
